#!/usr/bin/bash
shopt -s expand_aliases 
source ~/aa

tasks="rte mnli superglue-cb superglue-boolq stsb superglue-copa superglue-wic superglue-wsc.fixed imdb paws "
stasks="wnli qnli sst2 squad piqa qqp mrpc sst2"

exp1="_exp multi _pat _multi --learn_loaded_prompts=False --target_share=-1#1#0 --add_target=True"
exp2="_exp sep _pat  --learn_loaded_prompts=False --target_share=-1#1#0 --add_target=True"
exp3="_exp slr _pat _multi --learn_loaded_prompts=True --target_share=-1 _slr 0.001 --add_target=True"

exps=("$exp1" "$exp2" "$exp3")
exps=("$exp3")
for exp in "${exps[@]}"
do
   run="_cat $1 _tasks $tasks _stasks $stasks _ep 20 _tn 100 _bs 20  _temp ptar  _ppx 10100 $exp"
   if ! run $run ; then
      echo "exit 1"
      break
   fi
done


