REL_TO_PHRASE = {
    "oEffect":"effects on others are",
    "oReact":"then, others react",
    "oWant":"then, others want",
    "xAttr":"they are seen as",
    "xEffect":"effects on person are",
    "xIntent":"because they intended",
    "xNeed":"before that he requires",
    "xReact":"his reaction was",
    "xWant":"after they want",
    'AtLocation':"is located", 
    'ObjectUse':"is used for", 
    'Desires': "desire",
    'HasProperty':"has property", 
    'NotDesires': "no_desire", 
    'Causes':"causes", 
    'HasSubEvent':"<has_sub>", 
    'xReason':"for reason",
    'CapableOf':"<capable>", 
    'MadeUpOf':"<madeof>", 
    'isAfter':"<isAfter>", 
    'isBefore':"<isBefore>", 
    'isFilledBy': "<isFilledBy>",
    'HinderedBy':"<HinderedBy>",
    'cola':"Is it grammatical or meaningful",
}
REL_TO_SHARED_TOKENS = {
    "oEffect":"after others effect",
    "oReact":"after others react",
    "oWant":"after others want",
    "xAttr":"always they seen",
    "xEffect":"after they effect",
    "xIntent":"before they want",
    "xNeed":"before they need",
    "xReact":"after they react",
    "xWant":"after they want",
    'AtLocation':"is located", 
    'ObjectUse':"is used for", 
    'Desires': "desire",
    'HasProperty':"has property", 
    'NotDesires': "no_desire", 
    'Causes':"causes", 
    'HasSubEvent':"<has_sub>", 
    'xReason':"for reason",
    'CapableOf':"<capable>", 
    'MadeUpOf':"<madeof>", 
    'isAfter':"<isAfter>", 
    'isBefore':"<isBefore>", 
    'isFilledBy': "<isFilledBy>",
    'HinderedBy':"<HinderedBy>",
    'cola':"Is it grammatical or meaningful?",
}
REL_TO_WORD = {
    "oEffect":"effect on others",
    "oReact":"reaction of others",
    "oWant":"others want",
    "xAttr":"seen",
    "xEffect":"effect on them",
    "xIntent":"intend",
    "xNeed":"need",
    "xReact":"person reaction",
    "xWant":"want",
    'AtLocation':"location", 
    'ObjectUse':"use", 
    'Desires': "desire",
    'HasProperty':"property", 
    'NotDesires': "no_desire", 
    'Causes':"cause", 
    'HasSubEvent':"sub event", 
    'xReason':"reason",
    'CapableOf':"capable", 
    'MadeUpOf':"made of", 
    'isAfter':"is after", 
    'isBefore':"is before", 
    'isFilledBy': "is filled by",
    'HinderedBy':"hindered by",
    'cola':"Is it grammatical or meaningful?",
}
REL_TO_TOKEN = {
    "cb":"<cb>",
    "oEffect":"<oEffect>",
    "oReact":"<oReact>",
    "oWant":"<oWant>",
    "xAttr":"<xAttr>",
    "xEffect":"<xEffect>",
    "xIntent":"<xIntent>",
    "xNeed":"<xNeed>",
    "xReact":"<xReact>",
    "xWant":"<xWant>",
    'AtLocation':"<loc>", 
    'ObjectUse':"<use>", 
    'Desires': "<desire>",
    'HasProperty':"<prop>", 
    'NotDesires': "<no_desire>", 
    'Causes':"<cause>", 
    'HasSubEvent':"<has_sub>", 
    'xReason':"<xReason>",
    'CapableOf':"<capable>", 
    'MadeUpOf':"<madeof>", 
    'isAfter':"<isAfter>", 
    'isBefore':"<isBefore>", 
    'isFilledBy': "<isFilledBy>",
    'HinderedBy':"<HinderedBy>"
}
GEN_TOKENS = {
    "en": "<gen_en>",
    "fa": "<gen_fa>"
}
